- name: Clone a github repository
  git:
    repo: {{ peervpn_repo }}
    dest: {{ peervpn_base_dir }}
    clone: yes
    update: yes

- name: Copy builder
  template:
    src: build_peervpn.sh
    dest: {{ peervpn_base_dir }}
    owner: {{ owner_on_files }}
    group: {{ owner_on_files }}
    mode: '0755'

- name: Change perms
  file:
    path: {{ peervpn_base_dir }}
    owner: {{ owner_on_files }}
    group: {{ owner_on_files }}
    recurse: yes

- name: Install packages
  apt:
    name: {{ item }}
    state: present
  with_items: {{ packages_to_install }}

- name: Enable apache
  systemd:
    name: apache2
    state: started
    enabled: yes

- name: Build peervpn
  command: {{ peervpn_base_dir }}/build_peervpn.sh
