- name: Create a directory if it does not exist
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items: "{{ dirs_to_create }}"

- name: Copy "{{ peervpn_base_name }}"
  copy:
    src: "{{ peervpn_base_dir }}/{{ peervpn_base_name }}"
    dest: "{{ peervpn_debs_dir }}/{{ peervpn_base_name }}/{{ peervpn_bin_path }}/{{ peervpn_base_name }}"
    remote_src: yes
    mode: '0755'

- name: Copy control
  template:
    src: control.j2
    dest: "{{ peervpn_debs_dir }}/{{ peervpn_base_name }}/{{ peervpn_deb_config_dir }}/control"
    owner: "{{ owner_on_files }}"
    group: "{{ owner_on_files }}"
    mode: '0755'

- name: Copy deb repo source
  template:
    src: "{{ apr_source_repo_file_name }}.j2"
    dest: "{{ apt_source_path }}/{{ apr_source_repo_file_name }}"

- name: Build deb
  command: dpkg-deb --build "{{ peervpn_debs_dir }}/{{ peervpn_base_name }}"

- name: Copy deb
  copy: 
    src: "{{ peervpn_debs_dir }}/{{ peervpn_base_name }}.deb"
    dest: "{{ apache_deb_dir }}"
    remote_src: yes
    mode: '0755'

- name: Scan package
  shell: cd  "{{ apache_deb_dir }}"; dpkg-scanpackages . | gzip -c9  > "{{ apache_deb_dir }}/Packages.gz"

- name: Update repositories and install "peervpn"
  apt:
    name: peervpn
    update_cache: yes
