- name: Clone a github repository
  git:
    repo: "{{ peervpn_repo }}"
    dest: "{{ peervpn_base_dir }}"
    clone: yes
    update: yes

- name: Change perms
  file:
    path: "{{ peervpn_base_dir }}"
    owner: "{{ owner_on_files }}"
    group: "{{ owner_on_files }}"
    recurse: yes

- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages_to_install }}"

- name: Enable apache
  systemd:
    name: apache2
    state: started
    enabled: yes

- name: Download "{{ libressl_archive }}"
  get_url:
    url: "{{ libressl_archive_url }}/{{ libressl_archive }}"
    dest: "{{ peervpn_base_dir }}"
    mode: '0577'

- name: Extract "{{ libressl_archive }} into {{ peervpn_base_dir }}"
  unarchive:
    src: "{{ peervpn_base_dir }}/{{ libressl_archive }}"
    dest: "{{ peervpn_base_dir }}"

- name: Build libressl
  shell: "cd {{ peervpn_base_dir }}/{{ libressl_version }} && ./configure && make && cd .."

- name: Build peervpn
  shell: "cd {{ peervpn_base_dir }} ; cc -O2 -I{{ libressl_version }}/include peervpn.c -o peervpn {{ libressl_version }}/crypto/.libs/libcrypto.a"
