- name: Clone a github repository
  git:
    repo: "{{ peervpn_repo }}"
    dest: "{{ peervpn_base_dir }}"
    clone: yes
    update: yes

- name: Copy builder
  template:
    src: build_peervpn.sh
    dest: "{{ peervpn_base_dir }}"
    owner: "{{ owner_on_files }}"
    group: "{{ owner_on_files }}"
    mode: '0755'

- name: Change perms
  file:
    path: "{{ peervpn_base_dir }}"
    owner: "{{ owner_on_files }}"
    group: "{{ owner_on_files }}"
    recurse: yes

- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages_to_install }}"

- name: Enable apache
  systemd:
    name: apache2
    state: started
    enabled: yes

- name: Download libressl-2.5.1.tar.gz
  get_url:
    url: https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-2.5.1.tar.gz
    dest: "{{ peervpn_base_dir }}"
    mode: '0577'

- name: Extract libressl-2.5.1.tar.gz into "{{ peervpn_base_dir }}"
  ansible.builtin.unarchive:
    src: foo.tgz
    dest: "{{ peervpn_base_dir }}"

- name: Build libressl
  shell: "cd {{ peervpn_base_dir }}/libressl-2.5.1 && ./configure && make && cd .."

- name: Build peervpn
  shell: "cd {{ peervpn_base_dir }} ; cc -O2 -Ilibressl-2.5.1/include peervpn.c -o peervpn libressl-2.5.1/crypto/.libs/libcrypto.a"